name: Daily Codeforces Problem Commit

on:
  schedule:
    - cron: '15 5 * * *'  # Runs at 10:45 AM IST
  workflow_dispatch:

permissions:
  contents: write  # Ensure push access

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install jq -y

      - name: Fetch Codeforces Problem and Generate Solution
        run: |
          mkdir -p solutions
          export DAY=$(date +%Y-%m-%d)  # Export variable to use in other steps
          FILE="solutions/solution_$DAY.py"
          MDFILE="problems.md"

          response=$(curl -s "https://codeforces.com/api/problemset.problems")
          total=$(echo $response | jq '.result.problems | length')

          index=$((RANDOM % total))
          problem=$(echo $response | jq ".result.problems[$index]")

          name=$(echo $problem | jq -r '.name')
          contestId=$(echo $problem | jq -r '.contestId')
          index=$(echo $problem | jq -r '.index')
          url="https://codeforces.com/contest/$contestId/problem/$index"

          echo "## Problem for $DAY" >> $MDFILE
          echo "**[$name]($url)**" >> $MDFILE
          echo "" >> $MDFILE

          echo "# Solution for $DAY ($name)" > $FILE
          echo "def solve():" >> $FILE
          echo "    # TODO: Implement solution" >> $FILE
          echo "    print('Hello, Codeforces!')" >> $FILE
          echo "" >> $FILE
          echo "if __name__ == '__main__':" >> $FILE
          echo "    solve()" >> $FILE

      - name: Configure Git
        run: |
          git config --global user.name "MrigeshDeshpande"
          git config --global user.email "mrigeshdeshpande246+code@gmail.com"

      - name: Commit and Push Changes
        run: |
          git add solutions/solution_$(date +%Y-%m-%d).py problems.md
          git commit -m "Added Codeforces problem & solution for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
