name: Daily Codeforces Problem Commit

on:
  schedule:
    - cron: '15 5 * * *'  # Runs at 10:45 AM IST
  workflow_dispatch:

permissions:
  contents: write  # Ensure push access

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch Codeforces Problem and Generate Solution
        run: |
          mkdir -p solutions
          day=$(date +%Y-%m-%d)
          file="solutions/solution_$day.py"
          mdfile="problems.md"

          response=$(curl -s "https://codeforces.com/api/problemset.problems")
          total=$(echo $response | jq '.result.problems | length')

          index=$((RANDOM % total))
          problem=$(echo $response | jq ".result.problems[$index]")

          name=$(echo $problem | jq -r '.name')
          contestId=$(echo $problem | jq -r '.contestId')
          index=$(echo $problem | jq -r '.index')
          url="https://codeforces.com/contest/$contestId/problem/$index"

          echo "## Problem for $day" >> $mdfile
          echo "**[$name]($url)**" >> $mdfile
          echo "" >> $mdfile

          echo "# Solution for $day ($name)" > $file
          echo "def solve():" >> $file
          echo "    # TODO: Implement solution" >> $file
          echo "    print('Hello, Codeforces!')" >> $file
          echo "" >> $file
          echo "if __name__ == '__main__':" >> $file
          echo "    solve()" >> $file

      - name: Configure Git
        run: |
          git config --global user.name "MrigeshDeshpande"
          git config --global user.email "mrigeshdeshpande246+code@example.com"

      - name: Commit and Push Changes
        run: |
          git add solutions/solution_$day.py problems.md
          git commit -m "Added Codeforces problem & solution for $day" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MrigeshDeshpande/daily-coding-problems.git HEAD:main
